spring.application.name=recipes-helper

spring.datasource.url= jdbc:postgresql://localhost:5432/mydatabase
spring.jpa.database=POSTGRESQL
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=recipes-helper-db

spring.jpa.hibernate.ddl-auto=update
