spring.application.name=recipes-helper

# переменные окружения для запуска в docker 
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=recipes-helper-db

spring.jpa.hibernate.ddl-auto=update

jwt.secret=F9dRvKxZ2PqWmJtHsC4bN0YeTlUoXgI7SzEjQaVnDwM=